### ISSUE TITLE
Multible Databases  with different schemas not working

### ISSUE THREAD

**Issue by flomickl** [rsim/oracle-enhanced#2208]
### Steps to reproduce

I want to implement a multiple DB Setup where one model uses a different DB Schema (by using a different username and password). For this, I have a primary DB and a logs DB. 

The depending model in my example  is called FaLog with following based content

``
class FaLog < ApplicationRecord
end
``

My database.yaml has following setup:
```
default: &default
  adapter: oracle_enhanced
  host: <%=ENV['DB_HOST']%>
  port: <%=ENV['DB_PORT']%>
  database: <%=ENV['DB_NAME']%>

development:
  primary:
    <<: *default
    username: <%=ENV['DB_USER']%>
    password: <%=ENV['DB_PASS']%>
  logs:
    username: <%=ENV['DB_USER_LOG']%>
    password: <%=ENV['DB_PASS_LOG']%>
``` 

In both DB's exist the Table FA_LOGS already

If I connect via 'rails c'  and check FALog.last, I get an expected result.

According to the official documentation to use the multiple Databases I am adding following to my model
``
class FaLog < ApplicationRecord
  connects_to database: { write: :logs, reading: :logs }
end
``

If I connect again via 'rails c'  and check  `FALog.last` or any other command, I get 
``` 
retrieve_connection': No connection pool with 'FaLog' found. (ActiveRecord::ConnectionNotEstablished)
``` 

### Expected behavior
I would expect that the DB is connection is working like in the primary setup

### Actual behavior
The multiple database approach is not working, so the DB is not found. According to the error message.
I also used in the additional setup
``` 
#schema: <%=ENV['DB_SCHEMA_LOG']%>
``` 

### System configuration
**Rails version**: 6.0.3.7
**Oracle enhanced adapter version**: 6.0.6
**Ruby version**: Jruby 9.2.19 
**Oracle Database version**: 12.2.0.1.0
