### ISSUE TITLE
Reaper not detecting closed connections

### ISSUE THREAD

**Issue by lightswitch05** [rsim/oracle-enhanced#420]
Database connections die after an hour of inactivity - reaper doesn't detect the closed connections. After waiting on the dead connection for 15 minutes, rails throws an error and rebuilds the connection. The second request works as expected. Issue exists for both production & development.

I'm using an Oracle Enhanced (v1.5.2) JDBC connetion with Rails v4.1.0.beta1 running on jBoss 7 with jRuby 1.7.10 connecting to Oracle 11g Release 2 (11.2.0.4).
## database.yml

```
default: &default
  adapter: oracle_enhanced
  database: ****
  host: ****
  port: 1521
  username: ****
  password: ****
  reaping_frequency: 150 #seconds = 2.5 minutes

development:
  <<: *default
  pool: 5

production:
  <<: *default
  pool: 10
```
## Error

```
07:14:55,068 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/pricing_management]] (http--0.0.0.0-8280-1) 
Java::JavaSql::SQLRecoverableException (Closed Connection):
    oracle.jdbc.driver.PhysicalConnection.needLine(PhysicalConnection.java:6295)
    ....
    rubyjit.ActiveRecord::ConnectionAdapters::OracleEnhancedJDBCConnection::Cursor$$close_92C646BEB33B544DAAAC963FA7290D6A33D8EA591197350755.__file__(gems/gems/activerecord-oracle_enhanced-adapter-1.5.2/lib/active_record/connection_adapters/oracle_enhanced_jdbc_connection.rb:421)
```

[server.log](https://gist.github.com/lightswitch05/9231511#file-server-log), [Gemfile](https://gist.github.com/lightswitch05/9231511#file-gemfile), [Gemfile.lock](https://gist.github.com/lightswitch05/9231511#file-gemfile-lock), [Database.yml](https://gist.github.com/lightswitch05/9231511#file-database-yml)
