### ISSUE TITLE
ORA-12154: TNS:listener does not currently...

### ISSUE THREAD

**Issue by lcguida** [rsim/oracle-enhanced#516]
Hi. 

I have a Rails 2 app. In a local machine I was able to connect to orable database, no problem. 

I'm trying to update the server application. The database is in another machine. 

I have the following configuration in database.yml:

```
production:
  adapter: oracle_enhanced
  database: "mydbname"
  host: "my_hostname"
  port: 1521
  user: "my_user"
  password: "the_secret_one"
```

According to the README, If I'm not wrong, this configuration should not use TNS. (Because I'm using host and port). 

Am I doing something wrong? (I'm still verifying with database team if TNS is enabled there. I really don't understand much of oracle administration)

Version Info

```
rails 2.3.14
activerecord-oracle_enhanced-adapter 1.4.3
ruby-oci8 2.1.7


```
