### ISSUE TITLE
Oracle enhanced adapter ignores pool size

### ISSUE THREAD

**Issue by Bjoernsen** [rsim/oracle-enhanced#533]
I use 3 thin servers (behind an Nginx proxy) for my productive Rails app. Each of the thin servers produces 5 connections to the database. So my app has 15 connections in total. My Oracle admin complains that I use too many connections.

I do not know how to reduce the number of connections. I tried `pool: 2` in `database.yml`, and restarted all thin servers, but my app still produces 15 connections. It seems that the `pool` setting is not used at all.

Of course, I could reduce the number of thin server, but I would like to know how to use `pool`.

I have another Rails app using PostgreSQL. Here, this parameter works as expected.

I use Rails 4.1 and Ruby 2.1

```
production:
    adapter: oracle_enhanced
    database: "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=xxx)(PORT=12345)))(CONNECT_DATA=(SID=yyy)))"
    pool: 2
    username: ORACLE_USER
    password: ORACLE_PASSWORD
```
